### ISSUE TITLE
getUserFnMap findCall blowing the call stack for certain programs

### ISSUE THREAD

**Issue by nwinter** [codecombat/aether#143]
I busted down a more complex example and came up with this minimal test case:

```clojure
(defn fn1 [arg1]
  (.x arg1)
)

(defn fn2 [arg2]
  (.y arg2)
)
```

This dies [here](https://github.com/codecombat/aether/blob/master/src/transforms.coffee#L177-L177):

```
ERROR in transforms.getUserFnMap RangeError: Maximum call stack size exceeded
    at baseIsEqual (http://localhost:3000/javascripts/vendor.js:10259:25)
    at Function.isEqual (http://localhost:3000/javascripts/vendor.js:11548:14)
    at findCall (http://localhost:3000/javascripts/aether.js:24374:15)
    at findCall (http://localhost:3000/javascripts/aether.js:24384:24)
    at resolveVal (http://localhost:3000/javascripts/aether.js:24408:21)
    at findCall (http://localhost:3000/javascripts/aether.js:24373:16)
    at findCall (http://localhost:3000/javascripts/aether.js:24384:24)
    at resolveVal (http://localhost:3000/javascripts/aether.js:24408:21)
    at findCall (http://localhost:3000/javascripts/aether.js:24373:16)
    at findCall (http://localhost:3000/javascripts/aether.js:24384:24)
```

**Comment by Vlevo** [comment]
Put a "non-matching" function before or between and there is no error...
```
(defn fn0 [a b]  (* a b))
(defn fn1 [arg1] (.x arg1))
(defn fn2 [arg2] (.y arg2))
```
or
```
(defn fn1 [arg1] (.x arg1))
(defn fn0 [a b]  (* a b))
(defn fn2 [arg2] (.y arg2))
```
Move that non-matching function (in this case "fn0") to after the "fn{1|2}" and it is back to the error...

**Comment by nwinter** [comment]
Uh oh, it's happening in JavaScript, too.

```javascript
this.chooseTarget = function(friend) {
    this.say(friend);
    var nearest = friend.findNearestEnemy();
};

this.commandFriend = function() {
    this.chooseTarget();
};
```

@differentmatt no way am I going to be able to get this one before reproducing, and we are probably going to see it more and more as we get into all these function-based levels. Wanna check it out sometime in early May?

**Comment by differentmatt** [comment]
Yup, I'll take a look.

**Comment by Vlevo** [comment]
OK, now I'm getting a similar: ERROR in transforms.getUserFnMap

```
ERROR in transforms.getUserFnMap RangeError: Maximum call stack size exceeded
    at Array.toString (native)
    at h (http://direct.codecombat.com/javascripts/aether.js:2580:15)
    at s (http://direct.codecombat.com/javascripts/aether.js:2576:70)
    at s (http://direct.codecombat.com/javascripts/aether.js:2577:103)
    at h (http://direct.codecombat.com/javascripts/aether.js:2581:294)
    at s (http://direct.codecombat.com/javascripts/aether.js:2576:70)
    at s (http://direct.codecombat.com/javascripts/aether.js:2577:103)
    at h (http://direct.codecombat.com/javascripts/aether.js:2581:294)
    at s (http://direct.codecombat.com/javascripts/aether.js:2576:70)
    at s (http://direct.codecombat.com/javascripts/aether.js:2577:103)
```

I have scrunched my code down to the following:
```
(defn fn1 [arg1] (.x arg1))
(defn fn2 [arg1] (.x arg1))
```
It is not simply that the two functions are "idenitical" as my original functions are not and here is the mini-example:
```
(defn fn1 [arg1] (.x arg1))
(defn fn2 [arg1 arg2] (.x arg1) (.x arg2))
```
**There is now something about the first lines/statements being identical.....**

Making the first statement different is enough to get rid of the error:
```
(defn fn1 [arg1] (.x arg1))
(defn fn2 [arg1] (.y arg1))
```

**Comment by Vlevo** [comment]
Dang, I "lied" it only gets rid of it for the scrunched example, in my full code I still get the error, even though the fix couple of lines are different in my functions.

**Comment by differentmatt** [comment]
From @Vlevo 
> my default code for What in Carnation - Clojure, has the problem, but not Python, or Javascript  (I wrote the default code in Clojure then translated to python then that to javascript.)

**Comment by differentmatt** [comment]
I won't be able to look at this anytime soon, unless there is a common case in Python or JavaScript.

**Comment by Vlevo** [comment]
OK, I tried boiling down the aether output for my clojure code above, but that is so full of tmp this that and the other that I instead boiled down the output of Clojure.js and removed everything that didn't cause the error... (the aether output is of course the same just broken down into more tmps and so is harder to boil down)

I end up with this:
```
fn1 = function (arg1) {return arg1.x();};
fn2 = function (arg1) {return arg1.x();};
```

This comes from the following:
```
var fn1 = function (arg1) {
    return typeof arg1['x'] === 'function' && arg1['x'].length === 0 ? arg1['x']() : arg1['x'];
};
var fn2 = function (arg1) {
    return typeof arg1['x'] === 'function' && arg1['x'].length === 0 ? arg1['x']() : arg1['x'];
};
```
For some reason it thinks that "arg1.x" is a function "arg1.x()" and not a property "arg1.x"

This happens during the "compile" step so it doesn't matter what you are trying to pass into "arg1" (or if you ever try at all).

**Comment by Vlevo** [comment]
This is a "problem" in the javascript handling of calls to unassigned functions.

I found it because of how Clojure.js wraps up the (.x arg1) but still exists in javascript.

```
function peasant(id, callFunc) { return id.callFunc();}
function soldier(id, callFunc) { return id.callFunc();}
```
My intention is to use a loop on peasants or soldiers and call my function to call the peasant/soldiers functions.  Dumb, stupid, round about coding does not make it an non-existent error. :stuck_out_tongue_winking_eye:

Or maybe you'd prefer this snippet I stole from stackoverflow and doubled the function to produce the error :smile:
```
function addContact(id, refreshCallback) {
    refreshCallback();
    // blah blah
}

function remContact(id, refreshCallback) {
    refreshCallback();
    // blah blah
}

function refreshContactList() {
    alert('Hello World');
}
```

**Comment by Vlevo** [comment]
is Coffescript good enough?

I was trying to find the cause of one of the really funky errors in coffescript
![image](https://cloud.githubusercontent.com/assets/11031492/7870402/5e1c0fd0-0546-11e5-8096-223f046bedda.png)

so I started from scratch (empty) and pasted in my functions one at a time hoping to narrow done where I get my error and Hey, that looks familiar, but it starts with a different error:

Javascript console:
```
Simple loop not implemented for CoffeeScript
aether.js:21189 escodegen couldn't handle t.(anonymous function) {type: "Program", attr: Object, body: Array[1]} 
gave error: Error: Invalid mapping: {"generated":{"line":64,"column":30},"source":"plan","original":{"line":0,"column":0},"name":"accum$"}
aether.js:24500 ERROR in transforms.getUserFnMap RangeError: Maximum call stack size exceeded
    at Array.toString (native)
    at h (http://codecombat.com/javascripts/aether.js:2581:8)
    at s (http://codecombat.com/javascripts/aether.js:2576:70)
    at s (http://codecombat.com/javascripts/aether.js:2577:103)
    at h (http://codecombat.com/javascripts/aether.js:2581:294)
    at s (http://codecombat.com/javascripts/aether.js:2576:70)
    at s (http://codecombat.com/javascripts/aether.js:2577:103)
    at s (http://codecombat.com/javascripts/aether.js:2577:103)
    at h (http://codecombat.com/javascripts/aether.js:2581:294)
    at s (http://codecombat.com/javascripts/aether.js:2576:70)
```

not boiled down Coffeescript code

```
twoPi = 2 * Math.PI

@drawPolyStars = (center, radius, sides, skips, startAngle) ->
  angle = startAngle
  x = center.x
  y = center.y
  @toggleFlowers false 
  loops = skips + 1
  stepAngle = loops * (twoPi / sides)
  if skips != 0 and (sides % loops) == 0
    loops = skips
  endAngle = (twoPi * loops) + startAngle
  while angle <= endAngle
    newX = x + radius * Math.cos(angle)
    newY = y + radius * Math.sin(angle)
    @moveXY newX, newY 
    @toggleFlowers true 
    angle += stepAngle

@drawPolygon = (center, radius, sides, startAngle) ->
  @drawPolyStars center, radius, sides, 0, startAngle

@drawSpokes = (center, radius, sides, startAngle) ->
  x = center.x
  y = center.y
  endAngle = twoPi + startAngle
  stepAngle = twoPi / sides
  angle = startAngle
  while angle < endAngle
    newX = x + radius * Math.cos(angle)
    newY = y + radius * Math.sin(angle)
    if int(@pos.x) == int(x) and int(@pos.y) == int(y)
      @toggleFlowers true 
      @moveXY newX, newY 
    else
      @toggleFlowers false 
      @moveXY newX, newY 
      @toggleFlowers true 
      @moveXY x, y 
    @toggleFlowers false 
    angle += stepAngle

redX = {x: 28, y: 36}
whiteX = {x: 60, y: 36}

# --------------------------------------------------

@drawPolygon redX, 10, 6, twoPi/4
```

Hmm, I wonder if that would happen if I slowly pasted in my javascript functions...

no :frowning:  . . . WAIT . . . Clojure and coffescript are "this/@ -> hero" languages, where javascript is not.

Ha . . . if I use this.function, so I can use this -> hero, I don't get the error, but if I write "regular" functions and pass in "this" . . . YES!!...

```
ERROR in transforms.getUserFnMap RangeError: Maximum call stack size exceeded
    at Array.toString (native)
    at h (http://codecombat.com/javascripts/aether.js:2580:15)
    at s (http://codecombat.com/javascripts/aether.js:2576:70)
    at h (http://codecombat.com/javascripts/aether.js:2581:294)
    at s (http://codecombat.com/javascripts/aether.js:2576:70)
    at s (http://codecombat.com/javascripts/aether.js:2577:103)
    at h (http://codecombat.com/javascripts/aether.js:2581:294)
    at s (http://codecombat.com/javascripts/aether.js:2576:70)
    at s (http://codecombat.com/javascripts/aether.js:2577:103)
    at h (http://codecombat.com/javascripts/aether.js:2581:294)
```

Actual Code:
```
var twoPi = 2 * Math.PI;

drawPolyStars = function(center, radius, sides, skips, startAngle, me) {
    me.toggleFlowers(false);
    var angle = startAngle;
    var x = center.x;
    var y = center.y;
    var hoops = skips + 1;
    var stepAngle = hoops * (twoPi / sides);
    if(skips !== 0 && (sides % hoops) === 0) {
        hoops = skips;
    }
    var endAngle = (twoPi * hoops) + startAngle;
    while(angle <= endAngle) {
        var newX = x + radius * Math.cos(angle);
        var newY = y + radius * Math.sin(angle);
        me.moveXY(newX, newY);
        me.toggleFlowers(true);
        angle += stepAngle;
    }
};

drawPolygon = function(center, radius, sides, startAngle, me) {
    me.drawPolyStars(center, radius, sides, 0, startAngle, me);
};

drawSpokes = function(center, radius, sides, startAngle, me) {
    var x = center.x;
    var y = center.y;
    var endAngle = twoPi + startAngle;
    var stepAngle = twoPi / sides;
    var angle = startAngle;
    while(angle < endAngle) {
        var newX = x + radius * Math.cos(angle);
        var newY = y + radius * Math.sin(angle);
        if((me.pos.x|0) == (x|0) && (me.pos.y|0) == (y|0)) {
            me.toggleFlowers(true);
            me.moveXY(newX, newY);
        } else {
            me.toggleFlowers(false);
            me.moveXY(newX, newY);
            me.toggleFlowers(true);
            me.moveXY(x, y);
        }
        me.toggleFlowers(false);
        angle += stepAngle;
    }
};

redX = {x: 28, y: 36};
whiteX = {x: 60, y: 36};
```

OK, what about Python... (a "self -> hero" lang)

Nope, you? ( @differentmatt ) wrote it better :smiley: I can't get it to fail like the others, good job.

**Comment by differentmatt** [comment]
Confirmed this code yields call stack error:
```javascript
fn1 = function (arg1) { return arg1.x(); };
fn2 = function (arg1) { return arg1.x(); };
```
```sh
ERROR in transforms.getUserFnMap RangeError: Maximum call stack size exceeded
```

**Comment by fisch0920** [comment]
+1

**Comment by nwinter** [comment]
Fixed with @basicer's new Esper interpreter, since we no longer do the post-normalization transform that uses `getUserFnMap`.
